spectrocloud/CanvOS

- .arg
@3pings in the user experience section today. Some of the users got confused on where to update the `.arg` file. Some updated the comments section. Now that the README contains a markdown table with variable descriptions. I think we can prevent confusion by removing the extra content from the `.arg` file.
The `.arg` file would look like this:
```
CUSTOM_TAG=demo
IMAGE_REGISTRY=ttl.sh
OS_DISTRIBUTION=ubuntu
IMAGE_REPO=$OS_DISTRIBUTION
OS_VERSION=22   
K8S_DISTRIBUTION=k3s
ISO_NAME=palette-edge-installer
```
> chore: update .arg

- Earthfile
Uses the highest version kernel in the directory instead of the lowest. Otherwise the `apt upgrade` command has little value.
> Use highest kernel version

- Earthfile
latest versions of opensuse do not have mkinitrd and it's replaced / recommended to use dracut.
> replace mkinitrd with dracut

- Earthfile
This ensures the `/etc/cos/bootargs.cfg` file always is corrected if it is detected that selinux is enabled in it
> Always disable selinux

- Earthfile
If `se_linux=0` is disabled, then `apparmour` has to be present so that containerd can create containers.
> PE-2605 Adding apparmor-parser as se_linux is disabled

- Earthfile
We are using external kine so that we can share as much as code between postgresql and sqlite and also between kubeadm and k3s.
> Add kine to the base installation

- Earthfile
This is most like broken. Still need to test if I got all the ifs and elses propertly. Do not merge please.
> DRY configuration of postgresql

- slem/Dockerfile
- slem/README.md
- slem/build.sh
This script incorporates the changes for Kairos framework v2.4.3 & also takes into consideration the feedback we got from SUSE Rancher about the base image we've built with Kairos components. 
Feedback from SUSE:
We’ve had a look through the Dockerfile, along with the further details in the slides that you’ve shared with us, and we have a few concerns that I think are easily remedied:
1. We need you to build the image on a SLE Micro host, as what you’ve essentially done here is mixed SLES with SLE Micro from a package repo perspective, and whilst this will functionally work, it makes it much more challenging for us to support.
2. Following (1), we realise that when building on a SLE Micro host that you won’t have access to all the necessary packages, so we suggest that you pull the extra …
> Updated SLEM build script for Kairos v2.4.3

- slem/build.sh
Dockerfile attempts to include the following packages which are not part of SLEM repo. 
- nano
- systemd-network
- rng-tools
This PR has the fix to include the additional SUSE package repos for installing these packages
> Include SUSE PackageHub repos for additional packages

- earthly.sh
This PR mounts `~/.docker/config.json` to `/root/.docker/config.json` on the build container, allowing the build container to authenticate to remote registries. This is useful for pulling images from private registries. It could also be used to allow automatic pushing to private registries.
> Passthrough docker credentials

- Earthfile
I changed the Earthfile to allow for registries that point to spectro registered to be variables with defaults that can be overridden by customers if needed.  This allows customers the ability to use their own registries with our images cached.
> Updated Earthfile for registry variables

- earthly.sh
Please copy:
* `earthly/earthly:v0.8.5` to `gcr.io/spectro-images-public/earthly/earthly:v0.8.5`
* `earthly/buildkitd:v0.8.5` to `gcr.io/spectro-images-public/earthly/buildkitd:v0.8.5`
and then merge this PR. This uses the latest version of Earthly to reduce the number of CVEs in resulting images
> Update Earthly to 0.8.5

- Earthfile
> only use --debug if DEBUG=true

- .arg.template
cis_hardening needs to be enabled by the user and is disabled by default.
> disable cis_hardening

- earthly.sh
> PE-4702 fix: BYOS pack info doesn't get printed while building all images

- Earthfile
- overlay/files/etc/logrotate.d/stylus.conf
- overlay/files/etc/rsyslog.d/49-stylus.conf
Fixes the following issues:
1. /etc/logrotate.d/stylus.conf permission issue.
2. If /var/log has writable by group or others permission.
3. systemctl reload in rhel
> logrotate issue fix

- rhel-core-images/Dockerfile.rhel8.sat
- rhel-core-images/Dockerfile.rhel9
- rhel-core-images/Dockerfile.rhel9.sat
- rhel-core-images/README.md
- rhel-core-images/overlay/rhel9/system/oem/33_tmp_mount.yaml
Added RHEL 9 Dockerfile based on CanvOS 4.4 RHEL 8 Dockerfile (with updated Kairos Framework).
Added RHEL 9 and RHEL 8 Dockerfiles to build images with Red Hat Satellite/mirrored repositories
README file updated
> RHEL 9 Dockerfile + RHEL8/9 Dockerfiles to build with RH Satellite

- overlay/files/etc/logrotate.d/stylus.conf
Setting a size limit using 'size' did not respect time periods like daily, hourly, or yearly.
Changing `size` to `maxsize` will fix this
> PE-4832: changing size to maxsize

- cis-harden/harden.sh
Sets net.ipv4.conf.all.rp_filter=0 during CIS hardening to ensure CNIs don't break when `sysctl -p` is run at any point later on (such as Stylus Agent upgrades)
> Adjust net.ipv4.conf.all.rp_filter for CNI compatibility

- Earthfile
- earthly.sh
> PE-4701 use spectro alpine instead of offical one

- Earthfile
* Adjust PERL5LIB path so `psql` works interactively
* Adjust `/lib/systemd/system/postgresql@.service` so postgresql waits for the network to be online, in order to prevent situations where it doesn't bind to the IP address on the NIC.
> Postgresql fixes

- Earthfile
To ensure Stylus only starts at after reconfiguring it first
> Disable postgresql by default

- Earthfile
- earthly.sh
> PEM-5782 use ubuntu image instead of ubuntu-systemd

- .pre-commit-config.yaml
- Earthfile
> chore: bump provider k3s to 4.5.0-alpha1 and kubeadm to 4.5.0-alpha2

- Earthfile
> chore: bump provider k3s to 4.5.0-alpha2 and kubeadm to 4.5.0-alpha3

- Earthfile
- earthly-entrypoint.sh
- earthly.sh
> PE-5343: add earthly entrypoint script to fix build with proxy and cert

- ubuntu-fips/Dockerfile
OPS-6255: Updateed dockerfile to keep ubuntu pro tools installed
> OPS-6255: Update Dockerfile

- .arg.template
Changing format of DRDB variable to be consistent with other .arg versions
> Fix 'DRBD_VERSION' format in .arg.template
