.arg.template, Earthfile, README.md
=> Readme updates

Dockerfile
This PR adds the `-y` flag to the Dockerfile comments.
=> docs: updated Dockerfile comments

Earthfile, README.md, overlay/files-iso/boot/grub2/grub.cfg, rhel-core-images/Dockerfile.rhel8, rhel-core-images/overlay/rhel8/system/oem/33_tmp_mount.yaml, rhel-fips/Dockerfile, rhel-fips/README.md, rhel-fips/build.sh, rhel-fips/dracut.conf, rhel-fips/overlay/rhel8/system/oem/33_tmp_mount.yaml, ubuntu-fips/Dockerfile, ubuntu-fips/README.md, ubuntu-fips/build.sh, ubuntu-fips/dracut-broken-iscsi-ubuntu-20.patch, ubuntu-fips/dracut.conf, ubuntu-fips/pro-attach-config.yaml, ubuntu-fips/run.sh
get ubuntu fips, rhel core and rhel fips image docker files into canvos
=> add ubuntu fips, rhel core and rhel fips image docker files into canvos

Earthfile
Signed-off-by: Nianyu Shen <nianyu@spectrocloud.com>
=> PE-3060 add basic network utils

Earthfile
Signed-off-by: Nianyu Shen <nianyu@spectrocloud.com>
=> PE-3317 Add ethtool and tcpdump

Earthfile
openssl is used by TUI for authentication
=> PE-3818 install openssl for RHEL

.gitignore, Earthfile
=> PE-4280 fix kubeadm build

Earthfile
=> PE-4295 fix: content not copied into uki iso

.gitignore, Earthfile, README.md, earthly.sh, spectro-luet-auth.yaml.template
=> add support for private luet repo

README.md
=> docs: update readme for private reg

.gitignore
=> add efi-size-check/target/ to gitignore

Earthfile
=> fix custom tag

Earthfile
=> PE-4462 install rsync in uki provider base image

Earthfile
=> PE-4842 use etcdctl and luet from spectro third party image

Earthfile
Reverts spectrocloud/CanvOS#262
=> Revert "PAC-1983 new version of k8s 44c"

Earthfile
=> PE-4942 fix kubeadm-fips

Earthfile
=> fix fips image build

os_version.json
=> chore: bump opensuse to 15.6

Dockerfile
=> fix: copy cert in dockerfile

Earthfile
=> PE-5685 fix: rename fips framework image

Earthfile
=> PE-6330 fix: use --with-new-pkgs if UPDATE_KERNEL is set to true

earthly.sh
Check for docker config file before mounting volume in earthly.sh script
=> PE-6501: CanvOs earthly.sh script will create a problematic directory that can lead to build errors

ubuntu-fips/Dockerfile
Reverts spectrocloud/CanvOS#381
=> Revert "Update Dockerfile - add growpart package"

rhel-core-images/Dockerfile.rhel8, rhel-core-images/Dockerfile.rhel8.sat, rhel-core-images/Dockerfile.rhel9, rhel-core-images/Dockerfile.rhel9.sat
Reverts spectrocloud/CanvOS#379
=> Revert "Kairos version upgrade to v3.3.6"

Earthfile
Modify kairos-release file for SLEM
=> PE-7418: OS name displays incorrectly for slem in the edge host
